spring.application.name=springMVC
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:/Users/kiron/Pictures/springboot/db
spring.datasource.username=kronDB
spring.datasource.password=kiron1234
spring.jpa.hibernate.ddl-auto=update

